FROM quay.io/fedora/fedora-minimal:39

# DNF setup
RUN echo "assumeyes=True" >> /etc/dnf/dnf.conf

# Locale
RUN dnf5 install glibc-langpack-en
ENV LANG=en_US.utf8

# Vital packages
RUN dnf5 install \
  gzip \
  sudo \
  tar \
  util-linux

# Buildah and Podman
RUN dnf5 reinstall shadow-utils
RUN dnf5 install buildah podman --exclude container-selinux

# Docker
COPY --chown=root:root ./repos/docker-ce.repo /etc/yum.repos.d/docker-ce.repo
RUN chmod 0644 /etc/yum.repos.d/docker-ce.repo
RUN dnf5 install \
  docker-ce \
  docker-ce-cli \
  containerd.io \
  docker-buildx-plugin \
  docker-compose-plugin

# .NET Core dependencies
RUN dnf5 install \
  krb5-libs \
  libicu \
  lttng-ust \
  openssl-libs \
  zlib

# Remove DNF cache and logs
RUN dnf5 clean all
RUN rm -rf /var/log/dnf* /var/log/yum.*

# Runner user
RUN useradd -m runner && \
  usermod -aG wheel runner && \
  usermod -aG docker runner && \
  echo "%wheel ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER runner
