FROM quay.io/fedora/fedora:39

# DNF setup
RUN echo "assumeyes=True" >> /etc/dnf/dnf.conf

# Locale
ENV LANG=en_US.utf8

# Vital packages
RUN dnf install \
  gzip \
  sudo \
  tar \
  util-linux

# Buildah and Podman
RUN dnf install buildah podman

# Docker
COPY --chown=root:root ./repos/docker-ce.repo /etc/yum.repos.d/docker-ce.repo
RUN chmod 0644 /etc/yum.repos.d/docker-ce.repo
RUN dnf install \
  docker-ce \
  docker-ce-cli \
  containerd.io \
  docker-buildx-plugin \
  docker-compose-plugin

# .NET Core dependencies
RUN dnf install \
  krb5-libs \
  libicu \
  lttng-ust \
  openssl-libs \
  zlib

# Runner user
RUN useradd -m runner && \
  usermod -aG wheel runner && \
  usermod -aG docker runner && \
  echo "%wheel ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER runner
