name: "Fedora 39: build and push"

on:
  push:
    branches:
      - main
    paths:
      - images/fedora39/**
      - .github/workflows/fedora39-build-push.yml

env:
  IMAGE_NAME: oci-github-runner
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_OS: fedora-39
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_OS }} ${{ github.sha }}
          oci: true
          context: ./images/fedora39
          containerfiles: |
            ./images/fedora39/Containerfile

      - name: Push to registry
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
